[package]
name = "fula"
version = "0.1.0"
authors = ["Davis Silverman <davis.silverman@thehumangeo.com>"]

[dependencies]
rustful = "*"
hyper = "*"
log = "*"
env_logger = "*"
rustc-serialize = "*"

postgres="0.11.11"
